//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Airport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Высокий1 {
            get {
                object obj = ResourceManager.GetObject("Высокий1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Высокий2 {
            get {
                object obj = ResourceManager.GetObject("Высокий2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Высокий3 {
            get {
                object obj = ResourceManager.GetObject("Высокий3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Высокий4 {
            get {
                object obj = ResourceManager.GetObject("Высокий4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Высокий5 {
            get {
                object obj = ResourceManager.GetObject("Высокий5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Высокий6 {
            get {
                object obj = ResourceManager.GetObject("Высокий6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Высокий7 {
            get {
                object obj = ResourceManager.GetObject("Высокий7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Высокий8 {
            get {
                object obj = ResourceManager.GetObject("Высокий8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийВыход1 {
            get {
                object obj = ResourceManager.GetObject("ВысокийВыход1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийВыход2 {
            get {
                object obj = ResourceManager.GetObject("ВысокийВыход2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийВыход3 {
            get {
                object obj = ResourceManager.GetObject("ВысокийВыход3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийВыход4 {
            get {
                object obj = ResourceManager.GetObject("ВысокийВыход4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийВыход5 {
            get {
                object obj = ResourceManager.GetObject("ВысокийВыход5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСтрельба1 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСтрельба1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСтрельба2 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСтрельба2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумка1 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумка1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумка2 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумка2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумка3 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумка3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумка4 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумка4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумкаВыход1 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумкаВыход1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумкаВыход2 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумкаВыход2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумкаВыход3 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумкаВыход3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумкаВыход4 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумкаВыход4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийСумкаВыход5 {
            get {
                object obj = ResourceManager.GetObject("ВысокийСумкаВыход5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийЧемодан1 {
            get {
                object obj = ResourceManager.GetObject("ВысокийЧемодан1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийЧемодан2 {
            get {
                object obj = ResourceManager.GetObject("ВысокийЧемодан2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийЧемодан3 {
            get {
                object obj = ResourceManager.GetObject("ВысокийЧемодан3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ВысокийЧемодан4 {
            get {
                object obj = ResourceManager.GetObject("ВысокийЧемодан4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap конвеер1 {
            get {
                object obj = ResourceManager.GetObject("конвеер1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap конвеер2 {
            get {
                object obj = ResourceManager.GetObject("конвеер2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мент1 {
            get {
                object obj = ResourceManager.GetObject("Мент1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мент2 {
            get {
                object obj = ResourceManager.GetObject("Мент2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мент3 {
            get {
                object obj = ResourceManager.GetObject("Мент3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мент4 {
            get {
                object obj = ResourceManager.GetObject("Мент4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мент5 {
            get {
                object obj = ResourceManager.GetObject("Мент5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мент6 {
            get {
                object obj = ResourceManager.GetObject("Мент6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мент7 {
            get {
                object obj = ResourceManager.GetObject("Мент7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мент8 {
            get {
                object obj = ResourceManager.GetObject("Мент8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МентЧесть {
            get {
                object obj = ResourceManager.GetObject("МентЧесть", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мигалка1_1_ {
            get {
                object obj = ResourceManager.GetObject("Мигалка1_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мигалка1_2_ {
            get {
                object obj = ResourceManager.GetObject("Мигалка1_2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мигалка2_1_ {
            get {
                object obj = ResourceManager.GetObject("Мигалка2_1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мигалка2_2_ {
            get {
                object obj = ResourceManager.GetObject("Мигалка2_2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мужик1 {
            get {
                object obj = ResourceManager.GetObject("Мужик1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мужик2 {
            get {
                object obj = ResourceManager.GetObject("Мужик2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мужик3 {
            get {
                object obj = ResourceManager.GetObject("Мужик3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мужик4 {
            get {
                object obj = ResourceManager.GetObject("Мужик4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мужик5 {
            get {
                object obj = ResourceManager.GetObject("Мужик5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мужик6 {
            get {
                object obj = ResourceManager.GetObject("Мужик6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Мужик7 {
            get {
                object obj = ResourceManager.GetObject("Мужик7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикВыход1 {
            get {
                object obj = ResourceManager.GetObject("МужикВыход1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикВыход2 {
            get {
                object obj = ResourceManager.GetObject("МужикВыход2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикВыход3 {
            get {
                object obj = ResourceManager.GetObject("МужикВыход3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикВыход4 {
            get {
                object obj = ResourceManager.GetObject("МужикВыход4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикВыход5 {
            get {
                object obj = ResourceManager.GetObject("МужикВыход5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСтрельба1 {
            get {
                object obj = ResourceManager.GetObject("МужикСтрельба1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСтрельба2 {
            get {
                object obj = ResourceManager.GetObject("МужикСтрельба2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумка1 {
            get {
                object obj = ResourceManager.GetObject("МужикСумка1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумка2 {
            get {
                object obj = ResourceManager.GetObject("МужикСумка2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумка3 {
            get {
                object obj = ResourceManager.GetObject("МужикСумка3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумка4 {
            get {
                object obj = ResourceManager.GetObject("МужикСумка4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумкаВыход1 {
            get {
                object obj = ResourceManager.GetObject("МужикСумкаВыход1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумкаВыход2 {
            get {
                object obj = ResourceManager.GetObject("МужикСумкаВыход2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумкаВыход3 {
            get {
                object obj = ResourceManager.GetObject("МужикСумкаВыход3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумкаВыход4 {
            get {
                object obj = ResourceManager.GetObject("МужикСумкаВыход4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикСумкаВыход5 {
            get {
                object obj = ResourceManager.GetObject("МужикСумкаВыход5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикЧемодан1 {
            get {
                object obj = ResourceManager.GetObject("МужикЧемодан1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикЧемодан2 {
            get {
                object obj = ResourceManager.GetObject("МужикЧемодан2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикЧемодан3 {
            get {
                object obj = ResourceManager.GetObject("МужикЧемодан3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap МужикЧемодан4 {
            get {
                object obj = ResourceManager.GetObject("МужикЧемодан4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap сапер1 {
            get {
                object obj = ResourceManager.GetObject("сапер1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Сапер2 {
            get {
                object obj = ResourceManager.GetObject("Сапер2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Сапер3 {
            get {
                object obj = ResourceManager.GetObject("Сапер3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Сапер4 {
            get {
                object obj = ResourceManager.GetObject("Сапер4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Сапер5 {
            get {
                object obj = ResourceManager.GetObject("Сапер5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Сапер6 {
            get {
                object obj = ResourceManager.GetObject("Сапер6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Сапер7 {
            get {
                object obj = ResourceManager.GetObject("Сапер7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Сапер8 {
            get {
                object obj = ResourceManager.GetObject("Сапер8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Сапер9 {
            get {
                object obj = ResourceManager.GetObject("Сапер9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака1 {
            get {
                object obj = ResourceManager.GetObject("Собака1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака10 {
            get {
                object obj = ResourceManager.GetObject("Собака10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака11 {
            get {
                object obj = ResourceManager.GetObject("Собака11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака12 {
            get {
                object obj = ResourceManager.GetObject("Собака12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака2 {
            get {
                object obj = ResourceManager.GetObject("Собака2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака3 {
            get {
                object obj = ResourceManager.GetObject("Собака3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака4 {
            get {
                object obj = ResourceManager.GetObject("Собака4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака5 {
            get {
                object obj = ResourceManager.GetObject("Собака5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака6 {
            get {
                object obj = ResourceManager.GetObject("Собака6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака7 {
            get {
                object obj = ResourceManager.GetObject("Собака7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака8 {
            get {
                object obj = ResourceManager.GetObject("Собака8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Собака9 {
            get {
                object obj = ResourceManager.GetObject("Собака9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Тетка1 {
            get {
                object obj = ResourceManager.GetObject("Тетка1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Тетка2 {
            get {
                object obj = ResourceManager.GetObject("Тетка2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Толстый1 {
            get {
                object obj = ResourceManager.GetObject("Толстый1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Толстый2 {
            get {
                object obj = ResourceManager.GetObject("Толстый2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Толстый3 {
            get {
                object obj = ResourceManager.GetObject("Толстый3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Толстый4 {
            get {
                object obj = ResourceManager.GetObject("Толстый4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Толстый5 {
            get {
                object obj = ResourceManager.GetObject("Толстый5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Толстый6 {
            get {
                object obj = ResourceManager.GetObject("Толстый6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Толстый7 {
            get {
                object obj = ResourceManager.GetObject("Толстый7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйВыход1 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйВыход1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйВыход2 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйВыход2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйВыход3 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйВыход3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйВыход4 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйВыход4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСтрельба1 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСтрельба1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСтрельба2 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСтрельба2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСумка1 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСумка1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСумка2 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСумка2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСумка3 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСумка3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСумка4 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСумка4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСумкаВыход1 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСумкаВыход1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСумкаВыход2 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСумкаВыход2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСумкаВыход3 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСумкаВыход3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйСумкаВыход4 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйСумкаВыход4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйЧемодан1 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйЧемодан1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйЧемодан2 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйЧемодан2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйЧемодан3 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйЧемодан3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ТолстыйЧемодан4 {
            get {
                object obj = ResourceManager.GetObject("ТолстыйЧемодан4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Фон_Терминал {
            get {
                object obj = ResourceManager.GetObject("Фон_Терминал", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
